Update inspect method to handle nil serializable_hash
ruby-grape/grape-entity pull request #384
Opened 2024-04-28 09:52 UTC by fcce

`serializable_hash` may return `nil` 

before 
```ruby
Entities::User.represent nil
# An error occurred when inspecting the object: #<NoMethodError: undefined method `map' for nil:NilClass>
```
after 

```ruby
Entities::User.represent nil
#<Entities::User:326200 nil>
```

2024-05-02 18:43 UTC, dblock requested changes
Add a test and update CHANGELOG please?

2025-05-18 12:55 UTC, dblock approved these changes

2025-05-18 12:57 UTC, dblock commented
@numbata or @fcce want to finish this one?

2025-05-19 22:14 UTC, numbata commented on lib/grape_entity/entity.rb
> +        "#<#{self.class.name}:#{object_id}> nil"
As I know, the value of object preferable to keep inside the `<>`, so maybe this line shouldn't be like:
```suggestion
        "#<#{self.class.name}:#{object_id} nil>"
```
wdyt? 🤔

2025-05-24 13:42 UTC, merged

2025-05-24 13:42 UTC, dblock commented
Merged this, thanks for your help @numbata!